const stockSymbols = [
    'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'FB', 'TSLA', 'BRK.B', 'JNJ', 'V', 'WMT', 
    'JPM', 'PG', 'UNH', 'NVDA', 'DIS', 'PYPL', 'MA', 'HD', 'VZ', 'ADBE', 
    'NFLX', 'INTC', 'PFE', 'KO', 'T', 'MRK', 'PEP', 'NKE', 'XOM', 'ABT', 
    'CSCO', 'ORCL', 'COST', 'CVX', 'LLY', 'CRM', 'MCD', 'WFC', 'BAC', 'ACN',
    'MDT', 'TMO', 'AVGO', 'QCOM', 'UPS', 'LIN', 'NEE', 'HON', 'BMY', 'AMGN',
    'TXN', 'UNP', 'LOW', 'INTU', 'PM', 'IBM', 'SBUX', 'MMM', 'GE', 'AMD', 
    'AMAT', 'CAT', 'ISRG', 'MU', 'GS', 'BLK', 'ADI', 'LMT', 'SYK', 'SPGI',
    'RTX', 'BA', 'MS', 'MDLZ', 'DE', 'ZTS', 'NOW', 'VRTX', 'SCHW', 'BKNG', 
    'TGT', 'ANTM', 'PLD', 'ADP', 'C', 'MO', 'CI', 'CVS', 'TFC', 'MMC',
    'COP', 'APD', 'PNC', 'NSC', 'DHR', 'FDX', 'DUK', 'SO', 'LRCX', 'GILD',
    'EOG', 'CCI', 'ITW', 'CL', 'EL', 'CSX', 'ADI', 'ROP', 'NOC', 'SPG',
    'EW', 'ICE', 'HUM', 'MCO', 'EXC', 'BDX', 'WM', 'ADSK', 'TROW', 'FISV',
    'FIS', 'AON', 'SHW', 'MET', 'CME', 'NSC', 'BSX', 'CCI', 'BAX', 'APTV',
    'CMG', 'CDNS', 'SYY', 'AEP', 'ETN', 'AFL', 'CARR', 'EA', 'GPN', 'TT',
    'AIG', 'DG', 'EMR', 'MAR', 'PAYX', 'MCHP', 'ORLY', 'MSCI', 'APH', 'DD',
    'AME', 'CTSH', 'SLB', 'D', 'ECL', 'AZO', 'PPG', 'ANSS', 'TRV', 'PSA',
    'FTNT', 'MNST', 'DLR', 'WBA', 'VLO', 'HLT', 'PGR', 'EBAY', 'O', 'ZBH',
    'IDXX', 'ROP', 'ODFL', 'SRE', 'XEL', 'WELL', 'ROST', 'PEG', 'EXR', 'PRU',
    'MLM', 'KMB', 'IQV', 'TEL', 'KHC', 'CTAS', 'EFX', 'ETSY', 'FITB', 'OXY',
    'TDG', 'MTD', 'HES', 'WAT', 'MGM', 'XYL', 'HBAN', 'ULTA', 'MKTX', 'PXD',
    'FMC', 'NUE', 'PCAR', 'FAST', 'WST', 'SWK', 'IT', 'BALL', 'WDC', 'IR',
    'HIG', 'RMD', 'KEYS', 'GLW', 'AVY', 'CBRE', 'VRSK', 'BKR', 'CNC', 'CNP',
    'MOS', 'STX', 'PH', 'AEE', 'CDW', 'LUV', 'DOV', 'DRI', 'RSG', 'ATO',
    'ES', 'OKE', 'BF.B', 'BXP', 'COO', 'RF', 'TER', 'PEAK', 'ZBRA', 'WAB',
    'NDAQ', 'DRE', 'GWW', 'LNT', 'VTR', 'AES', 'CBOE', 'FE', 'MTB', 'JKHY',
    'TXT', 'BIO', 'KIM', 'GPC', 'EXPD', 'JCI', 'CMS', 'TSCO', 'CF', 'AKAM',
    'HST', 'LKQ', 'AIZ', 'OMC', 'BRO', 'TTWO', 'HII', 'CHRW', 'IPG', 'IP',
    'LYB', 'RJF', 'NVR', 'CLX', 'WAT', 'SEE', 'TSN', 'FFIV', 'STT', 'CPB',
    'J', 'TPR', 'HAS', 'LKQ', 'IRM', 'PKG', 'APA', 'F', 'KMX', 'AAL', 'MRO',
    'GNRC', 'VMC', 'A', 'NDSN', 'GPC', 'CTLT', 'SWKS', 'BR', 'WRB', 'JKHY',
    'MAS', 'NLOK', 'XRAY', 'PKI', 'ZION', 'LDOS', 'BHF', 'XRAY', 'QRVO', 'BWA',
    'HBI', 'MHK', 'TAP', 'NWL', 'WRK', 'HAS', 'IP', 'PFG', 'SYF', 'HRL',
    'NCLH', 'LEG', 'M', 'CMA', 'PNR', 'WU', 'DISH', 'ALK', 'FANG', 'ALK',
    'RCL', 'CAG', 'CZR', 'NWSA', 'WHR', 'NWS', 'LUMN', 'K', 'UNM', 'IVZ',
    'NLSN', 'FRT', 'UAA', 'MOS', 'TXT', 'BKR', 'FLS', 'SNA', 'DXC', 'BEN',
    'APA', 'AIG', 'HES', 'LUV', 'ZION', 'WYNN', 'RL', 'TXT', 'LEG', 'MHK',
    'AIV', 'FBHS', 'SEE', 'HFC', 'REZI', 'DVA', 'NRG', 'ALK', 'MTB', 'SLM'
  ];

export default stockSymbols;